name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          brew tap vitalyster/homebrew-header-only
          brew install autoconf autoconf-archive automake libtool libjson-rpc-cpp jsoncpp cppzmq lmdb glog gflags googletest protobuf openssl sqlite gloox
          brew link --force sqlite
      - name: Configure
        run: cmake .

      # Runs a set of commands using the runners shell
      - name: Make
        run: make
